Run cleanup
MapColonies/automation-cleanup-cli pull request #1
Opened 2023-06-29 12:28 UTC by shyeavr

fix cleanup tiles remover by adding the new tile storage method and make and add script for the CLI cleanup .

2023-06-29 12:38 UTC, dannysigalovich requested changes
Look on the comments. 
Are you sure that there is 1 exception?
(I Approve if you think its okey 👍 )

2023-06-29 12:38 UTC, dannysigalovich commented on Dockerfile1
Who is Jhon?

2023-06-29 12:38 UTC, dannysigalovich commented on cleanup_cli/app/executers.py
Fix the Indent please.

2023-06-29 12:38 UTC, dannysigalovich commented on cleanup_cli/sendbox_test.py
FIX indent

2023-06-29 12:38 UTC, dannysigalovich commented on cleanup_cli/wrappers/postgres.py
you can think of name as env param. 
if you prefer this way it okey too.

2023-06-29 12:38 UTC, dannysigalovich commented on cleanup_cli/wrappers/postgres.py
"Orthophoto"

2023-07-09 08:56 UTC, shyeavr commented on cleanup_cli/app/executers.py
bojamoi

2023-07-09 10:50 UTC, shyeavr commented
Finish

2023-07-09 10:50 UTC, closed without merging