Refactor cleanup
MapColonies/automation-cleanup-cli pull request #4
Opened 2024-09-15 13:25 UTC by tamarshelly2

Change cleanup code, Fix two bugs, and add a README file.

2024-09-22 13:12 UTC, shyeavr requested changes

2024-09-22 13:12 UTC, shyeavr commented on cleanup_cli/app/executers.py
> +def run_cleanup(deletion_list: List[dict], storage_handler, mapproxy_route, job_manager_route, raster_catalog_route, token, logger):
Add typing for all function parameters such as storage handler mapproxy route and so on

2024-09-22 13:12 UTC, shyeavr commented on cleanup_cli/app/executers.py
>              layer_id = layer['product_id']
Change to get function to ensure that the function will not return an exception for a key that is found - (get function returns none if the key isn't found) and handle None values cases

2024-09-22 13:12 UTC, shyeavr commented on cleanup_cli/app/executers.py
> +            logger.info(f"The layer: {identifier} had been cleaned with the results: {results[layer_id]} \n")
has been

2024-09-22 13:12 UTC, shyeavr commented on cleanup_cli/utils.py
> +def config_job_variables(job):
same as I mentioned above add typing and get function to all function logic

2024-09-22 13:12 UTC, shyeavr commented on cleanup_cli/utils.py
> +def delete_jobs_tasks_by_ids(job_manager_url: str, product_id: str, token: str):
Add docstring to describe the function

2024-09-22 13:12 UTC, shyeavr commented on cleanup_cli/utils.py
> +        return {"job_deleted" : "No jobs was found to delete"}
Add the product id to the return statement it can help us to follow the deletion process for each product id

2024-09-22 13:12 UTC, shyeavr commented on cleanup_script.py
> +def logDataToClean(logger,data_to_clean):
change the function name to Python convention (log_data_to_clean)

2024-09-22 13:12 UTC, shyeavr commented on cleanup_script.py
> +    layersIDs = []
same as I mentioned above - python syntax

2024-09-22 13:12 UTC, shyeavr commented on cleanup_script.py
> -log_file = f"{os.environ.get('LOGS_FILE_PATH')}/{current_date}"
It's better to get the LOGS_FILE_PATH env var from config file and use it by import

2024-09-22 13:12 UTC, shyeavr commented on cleanup_script.py
> -conf_dir = os.environ.get('CONF_FILE')
some as above

2024-11-04 12:48 UTC, tamarshelly2 commented
finish adding check for more than 1000 records of tiles

2024-11-04 12:49 UTC, tamarshelly2 commented
finish adding check for more than 1000 records o tiles

2025-01-23 15:07 UTC, tamarshelly2 commented on cleanup_cli/utils.py
> +        return {"job_deleted" : "No jobs was found to delete"}
the product_id is already printed in the logs and terminal, so there is no need to return the id here

2025-01-23 15:35 UTC, tamarshelly2 commented on cleanup_script.py
> -log_file = f"{os.environ.get('LOGS_FILE_PATH')}/{current_date}"
I initialize the logger before loading the configuration file to ensure logging is available if the configuration file is missing. For this reason, the log file path is defined outside the configuration file.

2025-01-23 15:36 UTC, tamarshelly2 commented on cleanup_script.py
> -conf_dir = os.environ.get('CONF_FILE')
I load the configuration file from an environment variable because it contains an api key, and I want to avoid committing it to git.

2025-01-26 07:33 UTC, shyeavr commented on cleanup_cli/utils.py
> +        return {"job_deleted" : "No jobs was found to delete"}
Is it logged for the job and task removment stage?
I mean it will be beneficial if for each stage we can see the events

2025-01-26 08:26 UTC, tamarshelly2 commented on cleanup_cli/utils.py
> +        return {"job_deleted" : "No jobs was found to delete"}
![Screenshot from 2025-01-26 10-15-14](https://github.com/user-attachments/assets/80bba002-25be-4c78-bd86-adfcf6a6b63d)
This is an example of the logger - you can see here that for each layer all the jobs and tasks are detailed

2025-01-29 13:43 UTC, merged